main: main.cpp
	g++ -std=c++26 -mmacosx-version-min=15.7 -Wall -Wno-unknown-pragmas -Wextra -pedantic -g -O2 -lpthread -fexperimental-library -o /tmp/main main.cpp
	#g++ -std=c++23  -Wall -Wno-unknown-pragmas -Wextra -pedantic -g -O2 -lpthread -o /tmp/main main.cpp
