#!/bin/bash

# Get all values from the MIB:
# snmpwalk -v 2c -c public localhost

# Get the hostname of the system:
#snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.1.5

# Get the hostname and kernel information:
#snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.1.1

# Get the network interface information:
#snmpwalk -v 2c 127.0.0.1 -c public .1.3.6.1.2.1.2.2.1.1

# Get the MAC address information:
# snmpwalk -v 2c 127.0.0.1 -c public .1.3.6.1.2.1.2.2.1.6

# Get a list of all network interfaces:
# snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.31.1.1.1.1

# Get the CPU information:
#snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.25.3.2.1.3 | grep -i cpu

# Get the system uptime information, run the following command:
snmpwalk -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.1.3.0
snmpget -v 2c -c public 127.0.0.1 .1.3.6.1.2.1.1.3.0

