#!/bin/bash

# Version information.
/usr/sbin/snmpd --version
if [ $? -ne 0 ]; then exit; fi

# Copy the MIB files to the default location to search for MIBs.
mkdir -p ~/.snmp/mibs
cp *.my ~/.snmp/mibs

# Translate part of MIB file.
TOID=ciscoLS1010ChassisFanLed
echo Translating $TOID
snmptranslate -m +ALL -IR -On $TOID
echo

# Man page: http://www.net-snmp.org/docs/man/snmpd.html
#LISTENER=tcp:6000
#LISTENER=udp:161
#echo Starting SNMP daemon
#/usr/sbin/snmpd -f -m +ALL -a -d -V -DALL $LISTENER

systemctl status snmpd

# sudo nano /etc/snmp/snmpd.conf

# Change:
# rocommunity  public default -V systemonly
# rocommunity6 public default -V systemonly
# To:
# rocommunity  public default
# rocommunity6 public default

# sudo systemctl restart snmpd
