#!/bin/bash

# Version information.
#/usr/sbin/snmpd --version
#if [ $? -ne 0 ]; then exit; fi

# Copy the configuration to the default location for it.
mkdir -p ~/.snmp
cp snmpd.conf ~/.snmp

# Copy the MIB files to the default location to search for MIBs.
mkdir -p ~/.snmp/mibs
cp mibs/* ~/.snmp/mibs

# Translate part of MIB file.
#TOID=shortErrorStatus.0
#echo Translating $TOID
#snmptranslate -On $TOID
#echo

# Man page: http://www.net-snmp.org/docs/man/snmpd.html
#LISTENER=udp:6000
#LISTENER=udp:161
LISTENER=udp:6001
echo Starting SNMP daemon
export MIBDIRS=/home/teus/.snmp/mibs
export MIBS=+ALL
/usr/sbin/snmpd -a -c ~/.snmp/snmpd.conf -d -f -m NTCIP1203-v0305 -V  $LISTENER


# snmpd -LOw -u Debian-snmp -g Debian-snmp -I -smux,mteTrigger,mteTriggerConf -f -p /run/snmpd.pid



# systemctl status snmpd

# sudo nano /etc/snmp/snmpd.conf

# Change:
# rocommunity  public default -V systemonly
# rocommunity6 public default -V systemonly
# To:
# rocommunity  public default
# rocommunity6 public default

# sudo systemctl restart snmpd
