#!/bin/bash

# See the tutorial at http://www.net-snmp.org/tutorial/tutorial-5/toolkit/mib_module/

# Copy the configurations to the default location for them.
mkdir -p ~/.snmp
if [ $? -ne 0 ]; then exit; fi
cp agent/snmpd.conf ~/.snmp
if [ $? -ne 0 ]; then exit; fi

# Copy the MIB files to the default location to search for MIBs.
mkdir -p ~/.snmp/mibs
if [ $? -ne 0 ]; then exit; fi
cp mibs/* ~/.snmp/mibs
if [ $? -ne 0 ]; then exit; fi
#cp net-snmp-5.9.1/mibs/* ~/.snmp/mibs/
#if [ $? -ne 0 ]; then exit; fi

# Copy the lassy_vms.h/.c into the mibsgroup.
cp agent/lassy_vms.* net-snmp-5.9.1/agent/mibgroup
if [ $? -ne 0 ]; then exit; fi

#export MIBS=+ALL
export MIBS=NTCIP1203-v0305

# Compile the Net-SNMP library as-is.
pushd net-snmp-5.9.1
echo | ./configure --with-mib-modules="lassy_vms"
if [ $? -ne 0 ]; then exit; fi
make --jobs=25
if [ $? -ne 0 ]; then exit; fi
popd

# Translate part of MIB file.
TOID=shortErrorStatus.0
echo -n "The OID $TOID is numeric OID: "
snmptranslate -IR -On shortErrorStatus.0

# Configure daemon for SNMP v3.
# $ snmpconf
# Create snmpd.conf
# Access Control Setup.
# SNMPv3 read-write user

