#!/bin/bash

g++ -Wall -Wextra -pedantic -std=c++17 -g -O2 -o html html.cpp `pkg-config libxml-2.0 gumbo tidy pugixml --libs --cflags`

#valgrind --leak-check=yes  --track-origins=yes --show-reachable=yes ./html
leaks -atExit -- ./html
#./html

rm -rf html
rm -rf html.dSYM
rm -rf *.o
