main: main.cpp
	#g++ -std=c++26 -mmacosx-version-min=15.7 -Wall -Wextra -Wpedantic -g -O2 -lpthread -fexperimental-library -o /tmp/main main.cpp
	g++ -std=c++26 -Wall -Wextra -Wpedantic -g -O2 -lpthread -o /tmp/main main.cpp
