#!/bin/bash

export ANDROID_HOME=~/scr/android-sdk-macosx
export PATH=$PATH:~/scr/android-sdk-macosx/platform-tools:~/scr/android-sdk-macosx/tools:~/scr/android-ndk-r10e

ant clean
if [ $? != 0 ]; then exit; fi

ant debug
if [ $? != 0 ]; then exit; fi

adb install -r bin/Laboratory-debug.apk
if [ $? != 0 ]; then exit; fi

adb shell am start -a android.intent.action.MAIN -n org.bibleconsultants.lab/.MainActivity
if [ $? != 0 ]; then exit; fi
